/* TODO APP*/
export const WATCH_TODO_LIST = "WATCH_TODO_LIST";
export const GET_TODO_LIST = "GET_TODO_LIST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const MARK_ALL_ITEMS = "MARK_ALL_ITEMS";
export const ADD_NEW_ITEM = "ADD_NEW_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SELECTED_ITEM = "SELECTED_ITEM";

/* ECOMMERRCE APP */
export const GET_LIST = "GET_LIST";
export const WATCH_PRODUCT_LIST = "WATCH_PRODUCT_LIST";
export const WATCH_SINGLE_ITEM = "WATCH_SINGLE_ITEM";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_SINGLE_ITEM = "GET_SINGLE_ITEM";
export const DECREMENT_QTY = "DECREMENT_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

/* Bookmark App */
export const WATCH_BOOKMARK_LIST = "WATCH_BOOKMARK_LIST";
export const GET_BOOKMARK_LIST = "GET_BOOKMARK_LIST";
export const ADD_TO_MY_BOOKMARK = "ADD_TO_MY_BOOKMARK";
export const ADD_NEW_BOOKMARK = "ADD_NEW_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const REMOVE_FROM_MY_BOOKMARK = "REMOVE_FROM_MY_BOOKMARK";
export const UPDATE_BOOKMARK = "UPDATE_BOOKMARK";
export const UPDATE_MY_BOOKMARK = "UPDATE_MY_BOOKMARK";

// Project
export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT";

/* Task App */

export const WATCH_TASK_LIST = "WATCH_TASK_LIST";
export const FETCH_ALL_TASK = "FETCH_ALL_TASK";
export const NEW_TASK = "NEW_TASK";
export const REMOVE_TASK = "REMOVE_TASK";

/* Cart */
export const ADD_TO_CART = "ADD_TO_CART";

/* Wishlist */
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

/* Filters */
export const FILTER_BRAND = "FILTER_BRAND";
export const FILTER_COLOR = "FILTER_COLOR";
export const FILTER_PRICE = "FILTER_PRICE";
export const SEARCH_BY = "SEARCH_BY";
export const SORT_BY = "SORT_BY";

/* CHAT APP */
export const GET_MEMBERS = "GET_MEMBERS";
export const WATCH_CHAT_MEMBERS = "WATCH_CHAT_MEMBERS";
export const WATCH_CHAT_SUCCESS = "WATCH_CHAT_SUCCESS";
export const WATCH_ALL_CHAT_SUCCESS = "WATCH_ALL_CHAT_SUCCESS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_CHATS = "GET_CHATS";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const UPDATE_SELECTED_USER = "UPDATE_SELECTED_USER";
export const CHANGE_CHAT = "CHANGE_CHAT";
export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_CHAT_WATCHER = "CREATE_CHAT_WATCHER";
export const SEARCH_MEMBER = "SEARCH_MEMBER";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_WATCHER = "SEND_MESSAGE_WATCHER";
export const REPLY_BY_SELECTED_USER = "REPLY_BY_SELECTED_USER";
export const REPLY_MESSAGE_WATCHER = "REPLY_MESSAGE_WATCHER";

/* Email-app */
export const WATCH_EMAIL = "WATCH_EMAIL";
export const WATCH_ALL_TYPE_EMAIL = "WATCH_ALL_TYPE_EMAIL";
export const GET_ALL_EMAIL_ASYN = "GET_ALL_EMAIL_ASYN";
export const GET_ALL_TYPE_ASYN = "GET_ALL_TYPE_ASYN";
export const GET_EMAILS = "GET_EMAILS";
export const GET_ALL_EMAILS = "GET_ALL_EMAILS";
export const GET_EMAIL_TYPES = "GET_EMAIL_TYPES";
export const UPDATE_EMAIL_TYPES = "UPDATE_EMAIL_TYPES";

export const CURRENT_LANGUAGE = "CURRENT_LANGUAGE";

/* CUSTOMIZER */
export const WATCH_CUSTOMIZER = "WATCH_CUSTOMIZER";
export const ADD_COSTOMIZER = "ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS = "ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIX_BACKGROUND_LAYOUT = "ADD_MIX_BACKGROUND_LAYOUT";
export const ROUTER_ANIMATION = "ROUTER_ANIMATION";

export const TOKEN_SET = "TOKEN_SET";
export const TOKEN_EXPIRY_TIME = "TOKEN_EXPIRY_TIME";

export const user_role_permission = "USER_ROLE_PERMISSION";

export const supplier_customer_cart = "Supplier_Customer_Cart";

export const supplier_customer_rectify_order =
  "Supplier_Customer_Rectify_Order";

export const USER_AUTH_TOKEN = "User_Auth_Token";
export const GET_STORES = "GET_STORES";
export const SIDEBAR_MENU_ITEMS = "SIDEBAR_MENU_ITEMS";

export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_INGREDIENTS = "Get_INGREDIENTS";

export const AddedIngredients = "AddedIngredients";

export const DeletedIngredient = "DeleteIngredient";

export const RemoveAllAddedIngredients = "RemoveAllAddedIngredients";
export const DashboardDetail = "DashboardDetail";
export const LeadLastForm = "LeadLastForm";

// --------------------------------

export const STORES_REVENUE_LIST = "STORES_REVENUE_LIST";

export const PRODUCTS_LIST = "PRODUCTS_LIST";
export const PRODUCTS_IS_BOX = "PRODUCTS_IS_BOX";
export const PRODUCTS_IS_SPECIAL = "PRODUCTS_IS_SPECIAL";
export const PRODUCTS_IS_ACTIVE = "PRODUCTS_IS_ACTIVE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCTS_BULK_DELETE = "PRODUCTS_BULK_DELETE";
export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_EDIT = "PRODUCT_EDIT";

export const PRODUCT_CATEGORIES_LIST = "PRODUCT_CATEGORIES_LIST";
export const PRODUCT_CATEGORIES_IS_ACTIVE = "PRODUCT_CATEGORIES_IS_ACTIVE";
export const PRODUCT_CATEGORIES_DELETE = "PRODUCT_CATEGORIES_DELETE";
export const PRODUCT_CATEGORIES_BULK_DELETE = "PRODUCT_CATEGORIES_BULK_DELETE";
export const PRODUCT_CATEGORIES_CREATE = "PRODUCT_CATEGORIES_CREATE";
export const PRODUCT_CATEGORIES_EDIT = "PRODUCT_CATEGORIES_EDIT";

export const INGREDIENTS_LIST = "INGREDIENTS_LIST";
export const INGREDIENT_IS_ACTIVE = "INGREDIENT_IS_ACTIVE";
export const INGREDIENT_DELETE = "INGREDIENT_DELETE";
export const INGREDIENTS_BULK_DELETE = "INGREDIENTS_BULK_DELETE";
export const INGREDIENTS_CREATE = "INGREDIENTS_CREATE";
export const INGREDIENTS_EDIT = "INGREDIENTS_EDIT";

export const INGREDIENT_CATEGORIES_LIST = "INGREDIENT_CATEGORIES_LIST";
export const INGREDIENT_CATEGORIES_IS_ACTIVE = "INGREDIENT_CATEGORIES_IS_ACTIVE";
export const INGREDIENT_CATEGORIES_DELETE = "INGREDIENT_CATEGORIES_DELETE";
export const INGREDIENT_CATEGORIES_BULK_DELETE = "INGREDIENT_CATEGORIES_BULK_DELETE";
export const INGREDIENT_CATEGORIES_CREATE = "INGREDIENT_CATEGORIES_CREATE";
export const INGREDIENT_CATEGORIES_EDIT = "INGREDIENT_CATEGORIES_EDIT";

export const LAYERS_LIST = "LAYERS_LIST";
export const LAYER_IS_ACTIVE = "LAYER_IS_ACTIVE";
export const LAYER_DELETE = "LAYER_DELETE";
export const LAYERS_BULK_DELETE = "LAYERS_BULK_DELETE";
export const LAYER_CREATE = "LAYER_CREATE";
export const LAYER_EDIT = "LAYER_EDIT";

export const ALLERGENS_LIST = "ALLERGENS_LIST";
export const ALLERGEN_IS_ACTIVE = "ALLERGEN_IS_ACTIVE";
export const ALLERGEN_DELETE = "ALLERGEN_DELETE";
export const ALLERGENS_BULK_DELETE = "ALLERGENS_BULK_DELETE";
export const ALLERGEN_CREATE = "ALLERGEN_CREATE";
export const ALLERGEN_EDIT = "ALLERGEN_EDIT";

export const PAGES_LIST = "PAGES_LIST";
export const PAGE_IS_ACTIVE = "PAGE_IS_ACTIVE";
export const PAGE_FOOTER_ACTIVE = "PAGE_FOOTER_ACTIVE";
export const PAGE_DELETE = "PAGE_DELETE";
export const PAGE_CREATE = "PAGE_CREATE";
export const PAGE_EDIT = "PAGE_EDIT";

export const STORE_DESCRIPTION_GET_DATA = "STORE_DESCRIPTION_GET_DATA";
export const STORE_DESCRIPTION_SAVE_DATA = "STORE_DESCRIPTION_SAVE_DATA";

export const INSTAGRAM_GET_DATA = "INSTAGRAM_GET_DATA";
export const INSTAGRAM_SAVE_DATA = "INSTAGRAM_SAVE_DATA";

export const TESTIMONIALS_LIST = "TESTIMONIALS_LIST";
export const TESTIMONIAL_DELETE = "TESTIMONIAL_DELETE";
export const TESTIMONIAL_CREATE = "TESTIMONIAL_CREATE";
export const TESTIMONIAL_EDIT = "TESTIMONIAL_EDIT";

export const STORES_LIST = "STORES_LIST";
export const STORE_DELETE = "STORE_DELETE";
export const STORE_CREATE = "STORE_CREATE";
export const STORE_EDIT = "STORE_EDIT";

export const SUPPLIER_CUSTOMERS_LIST = "SUPPLIER_CUSTOMERS_LIST";
export const SUPPLIER_CUSTOMER_DELETE = "SUPPLIER_CUSTOMER_DELETE";
export const SUPPLIER_CUSTOMER_CREATE = "SUPPLIER_CUSTOMER_CREATE";
export const SUPPLIER_CUSTOMER_EDIT = "SUPPLIER_CUSTOMER_EDIT";

export const SALES_ORDERS_LIST = "SALES_ORDERS_LIST";
export const SALES_ORDER_CHANGE_STATUS = "SALES_ORDER_CHANGE_STATUS";
export const SALES_ORDER_CHANGE_STATUS_CHECK = "SALES_ORDER_CHANGE_STATUS_CHECK";
export const SALES_ORDER_CREATE = "SALES_ORDER_CREATE";
export const SALES_ORDER_EDIT = "SALES_ORDER_EDIT";

export const COUPONS_LIST = "COUPONS_LIST";
export const COUPON_IS_ACTIVE = "COUPON_IS_ACTIVE";
export const COUPON_DELETE = "COUPON_DELETE";
export const COUPONS_BULK_DELETE = "COUPONS_BULK_DELETE";
export const COUPON_CREATE = "COUPON_CREATE";
export const COUPON_EDIT = "COUPON_EDIT";

export const SALES_CUSTOMERS_LIST = "SALES_CUSTOMERS_LIST";
export const SALES_CUSTOMER_DELETE = "SALES_CUSTOMER_DELETE";
export const SALES_CUSTOMER_CREATE = "SALES_CUSTOMER_CREATE";
export const SALES__CUSTOMER_EDIT = "SALES__CUSTOMER_EDIT";

export const SUPPLIERS_ORDERS_LIST = "SUPPLIERS_ORDERS_LIST";

export const LOGS_LIST = "LOGS_LIST";

export const EMAILS_LIST = "EMAILS_LIST";

export const LEADS_LIST = "LEADS_LIST";
export const LEAD_DELETE = "LEAD_DELETE";
export const LEAD_CREATE = "LEAD_CREATE";
export const LEAD_EDIT = "LEAD_EDIT";

export const SUPPLIER_ORDER_TOKEN_VERIFICATION = "SUPPLIER_ORDER_TOKEN_VERIFICATION";
export const SUPPLIER_ORDER_ITEM_MODIFY = "SUPPLIER_ORDER_ITEM_MODIFY";
export const SUPPLIER_ORDER_ITEM_REMOVE = "SUPPLIER_ORDER_ITEM_REMOVE";
export const SUPPLIER_ORDER_TOKEN_VERIFICATION_CLEAR = "SUPPLIER_ORDER_TOKEN_VERIFICATION_CLEAR";

export const RECTIFY_ORDER_DATA = "RECTIFY_ORDER_DATA";
export const RECTIFY_ORDER_DELETE = "RECTIFY_ORDER_DELETE";
export const RECTIFY_ORDER_DATA_CLEAR = "RECTIFY_ORDER_DATA_CLEAR";

export const SUPPLIER_CUSTOMER_CART_DATA = "SUPPLIER_CUSTOMER_CART_DATA";
export const SUPPLIER_CUSTOMER_CART_ITEM_DELETE = "SUPPLIER_CUSTOMER_CART_ITEM_DELETE";
export const SUPPLIER_CUSTOMER_CART_DATA_CLEAR = "SUPPLIER_CUSTOMER_CART_DATA_CLEAR";

/** *********************************** Global Settings *********************************** */

export const GENERAL_SETTINGS_GET_DATA = "GENERAL_SETTINGS_GET_DATA";
export const GENERAL_SETTINGS_SAVE_DATA = "GENERAL_SETTINGS_SAVE_DATA";

export const ZELTY_SETTINGS_GET_DATA = "ZELTY_SETTINGS_GET_DATA";
export const ZELTY_SETTINGS_SAVE_DATA = "ZELTY_SETTINGS_SAVE_DATA";

export const STRIPE_PAYMENT_GET_DATA = "STRIPE_PAYMENT_GET_DATA";
export const STRIPE_PAYMENT_SAVE_DATA = "STRIPE_PAYMENT_SAVE_DATA";

export const PAYPAL_PAYMENT_GET_DATA = "PAYPAL_PAYMENT_GET_DATA";
export const PAYPAL_PAYMENT_SAVE_DATA = "PAYPAL_PAYMENT_SAVE_DATA";

export const ECCOM_SEO_GET_DATA = "ECCOM_SEO_GET_DATA";
export const ECCOM_SEO_SAVE_DATA = "ECCOM_SEO_SAVE_DATA";

export const UNITS_LIST = "UNITS_LIST";
export const UNIT_IS_ACTIVE = "UNIT_IS_ACTIVE";
export const UNIT_DELETE = "UNIT_DELETE";
export const UNIT_CREATE = "UNIT_CREATE";
export const UNIT_EDIT = "UNIT_EDIT";

export const SHIPPING_COMPANIES_LIST = "SHIPPING_COMPANIES_LIST";
export const SHIPPING_COMPANY_DELETE = "SHIPPING_COMPANY_DELETE";
export const SHIPPING_COMPANY_CREATE = "SHIPPING_COMPANY_CREATE";
export const SHIPPING_COMPANY_EDIT = "SHIPPING_COMPANY_EDIT";

export const SUPPLIERS_LIST = "SUPPLIERS_LIST";
export const SUPPLIER_DELETE = "SUPPLIER_DELETE";
export const SUPPLIER_CREATE = "SUPPLIER_CREATE";
export const SUPPLIER_EDIT = "SUPPLIER_EDIT";

export const RULES_LIST = "RULES_LIST";
export const RULE_DELETE = "RULE_DELETE";
export const RULE_CREATE = "RULE_CREATE";
export const RULE_EDIT = "RULE_EDIT";

export const ASSOCIATE_RULES_LIST = "ASSOCIATE_RULES_LIST";
export const ASSOCIATE_RULE_DELETE = "ASSOCIATE_RULE_DELETE";
export const ASSOCIATE_RULE_CREATE = "ASSOCIATE_RULE_CREATE";
export const ASSOCIATE_RULE_EDIT = "ASSOCIATE_RULE_EDIT";

export const FOOTER_SIGNATURE_GET_DATA = "FOOTER_SIGNATURE_GET_DATA";
export const FOOTER_SIGNATURE_SAVE_DATA = "FOOTER_SIGNATURE_SAVE_DATA";

export const GALLERY_IMAGES_GET_DATA = "GALLERY_IMAGES_GET_DATA";
export const GALLERY_IMAGES_SUBMIT_LOADING = "GALLERY_IMAGES_SUBMIT_LOADING";
export const GALLERY_IMAGES_DATA_DELETE = "GALLERY_IMAGES_DATA_DELETE";
export const GALLERY_IMAGES_SAVE_DATA = "GALLERY_IMAGES_SAVE_DATA";

export const STAGE_FORMS_LIST = "STAGE_FORMS_LIST";
export const STAGE_FORM_DELETE = "STAGE_FORM_DELETE";
export const STAGE_FORM_CREATE = "STAGE_FORM_CREATE";
export const STAGE_FORM_EDIT = "STAGE_FORM_EDIT";

export const LEAD_FORMS_LIST = "LEAD_FORMS_LIST";
export const LEAD_FORM_DELETE = "LEAD_FORM_DELETE";
export const LEAD_FORM_CREATE = "LEAD_FORM_CREATE";
export const LEAD_FORM_EDIT = "LEAD_FORM_EDIT";

export const ADMINS_LIST = "ADMINS_LIST";
export const ADMIN_DELETE = "ADMIN_DELETE";
export const ADMIN_CREATE = "ADMIN_CREATE";
export const ADMIN_EDIT = "ADMIN_EDIT";

export const ROLES_LIST = "ROLES_LIST";
export const ROLE_DELETE = "ROLE_DELETE";
export const ROLE_CREATE = "ROLE_CREATE";
export const ROLE_EDIT = "ROLE_EDIT";

/** **************************************************************************** */




