export const ADD_CAROUSEL_DATA = "ADD_CAROUSEL_DATA";
export const ALL_CAROUSEL_DATA = "ALL_CAROUSEL_DATA";
export const SUBMIT_CAROUSEL_DATA = "SUBMIT_CAROUSEL_DATA";
export const EDIT_CAROUSEL_DATA = "EDIT_CAROUSEL_DATA";
export const DELETE_CAROUSEL_DATA = "DELETE_CAROUSEL_DATA";
